version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  reviewers:
  - marco-streng
  ignore:
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.20.1
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.31.0
    - 5.32.0
    - 5.34.0
    - 5.35.0
    - 5.36.0
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: html-webpack-plugin
    versions:
    - 5.0.0
    - 5.1.0
    - 5.2.0
    - 5.3.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
    - 7.13.0
