name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: publish prerelease
        if: "github.event.release.prerelease"
        run: |
          yarn install
          yarn lint
          yarn test
          yarn build
          npm publish --tag next
      - name: publish release
        if: "!github.event.release.prerelease"
        run: |
          yarn install
          yarn lint
          yarn test
          yarn build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
